import "../css/Home.css"
import Footer from "./Footer"
import Header from "./Header"

function Home() {
    return(
        <>
            <Header/>
                <main className="mainHome">
                    <h1>A febre dos álbuns de figurinhas</h1>
                    <h3>Apesar de antiga, a prática de colecionar figurinhas continua em alta entre várias faixas etárias!</h3>

                    <section>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ratione doloremque eligendi nesciunt blanditiis accusamus reprehenderit ullam perferendis, distinctio obcaecati error praesentium repellendus! Tempore asperiores nesciunt velit debitis assumenda dolorum ex! Lorem ipsum dolor, sit amet consectetur adipisicing elit. Itaque dolorum a enim blanditiis provident totam culpa quo odit placeat natus similique, ipsum ab eum nulla deserunt necessitatibus eaque corrupti esse! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptates aliquam deleniti reprehenderit veritatis quam accusantium ipsa numquam? Nobis, ab provident hic officiis corrupti quibusdam at necessitatibus animi vitae totam accusamus. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolor dolorum totam, enim quod hic quae mollitia pariatur nam. Architecto veritatis soluta voluptate velit optio aspernatur vero incidunt necessitatibus a porro. Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, veniam dicta cum esse error maiores cumque aliquam aliquid quis ab asperiores fugit illum provident enim numquam reiciendis placeat tenetur sapiente. Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum deleniti, quisquam error praesentium minima, tempora nam maxime vero reiciendis libero beatae aliquam fuga. Doloremque nulla dolor blanditiis voluptates quo animi! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Cupiditate unde iure, ipsum fugit debitis distinctio veniam consequatur fuga quas laborum nobis exercitationem provident quod? Sit nemo laborum quo reprehenderit molestias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit magnam recusandae id architecto fugiat culpa vitae, eveniet tempore tempora corporis temporibus provident cumque rerum! Suscipit omnis quia facere! Consectetur, quae. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione totam voluptatibus minus non temporibus veritatis, quo rerum. Ducimus ratione cum dignissimos labore qui. Ipsam rem voluptate cupiditate! Fugit, nostrum incidunt. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Natus a rerum in recusandae deserunt? Hic cumque explicabo repellendus voluptatum impedit dolorum, amet cupiditate illum dolorem quaerat aut provident, excepturi quae! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempora consequatur harum repellat? Ipsa, tempora dolorum, autem laboriosam voluptas eius excepturi id modi voluptates sed eum iusto iste! Veritatis, debitis? Fugiat? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eos eveniet nihil blanditiis tempore quas quasi nobis officiis iure non. Vel incidunt molestiae quam corporis placeat nobis? Id earum repellat aut. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed dolorem voluptatibus sit consequuntur rem error asperiores maxime repellat quasi odio debitis vitae possimus earum eaque, blanditiis aperiam quibusdam, mollitia quas.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ratione doloremque eligendi nesciunt blanditiis accusamus reprehenderit ullam perferendis, distinctio obcaecati error praesentium repellendus! Tempore asperiores nesciunt velit debitis assumenda dolorum ex! Lorem ipsum dolor, sit amet consectetur adipisicing elit. Itaque dolorum a enim blanditiis provident totam culpa quo odit placeat natus similique, ipsum ab eum nulla deserunt necessitatibus eaque corrupti esse! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptates aliquam deleniti reprehenderit veritatis quam accusantium ipsa numquam? Nobis, ab provident hic officiis corrupti quibusdam at necessitatibus animi vitae totam accusamus. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolor dolorum totam, enim quod hic quae mollitia pariatur nam. Architecto veritatis soluta voluptate velit optio aspernatur vero incidunt necessitatibus a porro. Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, veniam dicta cum esse error maiores cumque aliquam aliquid quis ab asperiores fugit illum provident enim numquam reiciendis placeat tenetur sapiente. Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum deleniti, quisquam error praesentium minima, tempora nam maxime vero reiciendis libero beatae aliquam fuga. Doloremque nulla dolor blanditiis voluptates quo animi! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Cupiditate unde iure, ipsum fugit debitis distinctio veniam consequatur fuga quas laborum nobis exercitationem provident quod? Sit nemo laborum quo reprehenderit molestias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit magnam recusandae id architecto fugiat culpa vitae, eveniet tempore tempora corporis temporibus provident cumque rerum! Suscipit omnis quia facere! Consectetur, quae. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione totam voluptatibus minus non temporibus veritatis, quo rerum. Ducimus ratione cum dignissimos labore qui. Ipsam rem voluptate cupiditate! Fugit, nostrum incidunt. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Natus a rerum in recusandae deserunt? Hic cumque explicabo repellendus voluptatum impedit dolorum, amet cupiditate illum dolorem quaerat aut provident, excepturi quae! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempora consequatur harum repellat? Ipsa, tempora dolorum, autem laboriosam voluptas eius excepturi id modi voluptates sed eum iusto iste! Veritatis, debitis? Fugiat? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eos eveniet nihil blanditiis tempore quas quasi nobis officiis iure non. Vel incidunt molestiae quam corporis placeat nobis? Id earum repellat aut. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed dolorem voluptatibus sit consequuntur rem error asperiores maxime repellat quasi odio debitis vitae possimus earum eaque, blanditiis aperiam quibusdam, mollitia quas.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ratione doloremque eligendi nesciunt blanditiis accusamus reprehenderit ullam perferendis, distinctio obcaecati error praesentium repellendus! Tempore asperiores nesciunt velit debitis assumenda dolorum ex! Lorem ipsum dolor, sit amet consectetur adipisicing elit. Itaque dolorum a enim blanditiis provident totam culpa quo odit placeat natus similique, ipsum ab eum nulla deserunt necessitatibus eaque corrupti esse! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptates aliquam deleniti reprehenderit veritatis quam accusantium ipsa numquam? Nobis, ab provident hic officiis corrupti quibusdam at necessitatibus animi vitae totam accusamus. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolor dolorum totam, enim quod hic quae mollitia pariatur nam. Architecto veritatis soluta voluptate velit optio aspernatur vero incidunt necessitatibus a porro. Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, veniam dicta cum esse error maiores cumque aliquam aliquid quis ab asperiores fugit illum provident enim numquam reiciendis placeat tenetur sapiente. Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum deleniti, quisquam error praesentium minima, tempora nam maxime vero reiciendis libero beatae aliquam fuga. Doloremque nulla dolor blanditiis voluptates quo animi! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Cupiditate unde iure, ipsum fugit debitis distinctio veniam consequatur fuga quas laborum nobis exercitationem provident quod? Sit nemo laborum quo reprehenderit molestias. Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit magnam recusandae id architecto fugiat culpa vitae, eveniet tempore tempora corporis temporibus provident cumque rerum! Suscipit omnis quia facere! Consectetur, quae. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione totam voluptatibus minus non temporibus veritatis, quo rerum. Ducimus ratione cum dignissimos labore qui. Ipsam rem voluptate cupiditate! Fugit, nostrum incidunt. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Natus a rerum in recusandae deserunt? Hic cumque explicabo repellendus voluptatum impedit dolorum, amet cupiditate illum dolorem quaerat aut provident, excepturi quae! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempora consequatur harum repellat? Ipsa, tempora dolorum, autem laboriosam voluptas eius excepturi id modi voluptates sed eum iusto iste! Veritatis, debitis? Fugiat? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eos eveniet nihil blanditiis tempore quas quasi nobis officiis iure non. Vel incidunt molestiae quam corporis placeat nobis? Id earum repellat aut. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed dolorem voluptatibus sit consequuntur rem error asperiores maxime repellat quasi odio debitis vitae possimus earum eaque, blanditiis aperiam quibusdam, mollitia quas.</p>
                    </section>
                </main>
            <Footer/>
        </>
    )
}

export default Home